#!/bin/bash
# Version 0.8

[ -f .moduleconfig ] || exit 2
source .moduleconfig || exit 3

MODULE_FILES="$( find ${MODULE_DIRS} -type f | grep -vf ${MODULE_IGNORE} )"
NEWEST_FILE=$( ls -1t ${MODULE_FILES} | head -1 )
VERSION=$( head ${NEWEST_FILE} | grep Version | sed -e 's:.*Version :Version :' -e 's: (.*::' )

if [ ${NEWEST_FILE} -ot ${MODULE_CONTROL} -a ! -f .preupd_unfinished ] ; then
    echo >&2 "no files have changed since last update push"
    exit 4
fi

# build FHEM's control file
touch .preupd_unfinished
while read GIT_STATUS GIT_FILENAME garbage ; do
    [ $( echo "${GIT_STATUS}" | grep -c [DR] ) -eq 1 ] && echo "DEL ./${GIT_FILENAME}"
done < <( git status --porcelain ) >>${MODULE_DELETES}
cat ${MODULE_DELETES} | sort -u >${MODULE_CONTROL}
while read MODULE_FILE ; do
    echo "UPD $( date -r ${MODULE_FILE} +%F_%T ) $( stat -c %s ${MODULE_FILE} ) ${MODULE_FILE}"
done < <( echo "${MODULE_FILES}" ) >>${MODULE_CONTROL}

# update HISTORY file
echo $( date +%F\ %T\ %z ) ${VERSION} >HISTORY
git log --pretty=format:'%ci %s' ${MODULE_FILES} ${MODULE_CONTROL} | sort -ru >>HISTORY

# update CHANGED file
echo "FHEM module ${MODULE} last 3 changes:" >CHANGED
cat HISTORY \
    | sed -E -e 's:^([0-9-]*) [0-9:]* [+-][0-9]* (Version.*):\1\: \2:' -e 's:^[0-9 :-]* [+-][0-9]* : - :' \
    | awk '/: Version /{c=c+1}c==4{exit}{print}' >>CHANGED

while : ; do
	echo "=====> BEGIN FHEM <====="
	cat ${MODULE_CONTROL}
	echo "=====> BEGIN CHANGES <====="
	cat CHANGED
	echo "=========="
	read -p "Content ok [yen]: "
	case "${REPLY}" in
    	    ([yY]*)
		# update git
		git add ${MODULE_CONTROL} CHANGED HISTORY
		git commit -m "${VERSION}"
		git push
		rm .preupd_unfinished
		exit
		;;
    	    ([eE]*)
		vim ${MODULE_CONTROL} CHANGED
		;;
    	    (*)
		echo >&2 "aborting module update"
		exit 1
		;;
	esac
done

