#!/bin/bash   
while read newfile ; do
	echo "DEL ${newfile}"
	echo "UPD $( date -r ${newfile} +%F_%T ) $( stat -c %s ${newfile} ) ${newfile}"
done < <( find ./FHEM/ ./images/ -type f ) >SST.txt

# update CHANGED file
$(
	echo "FHEM SST last changes:" > CHANGED
	date +%F >> CHANGED
	echo " - $(git log -1 --pretty=%B)" >> CHANGED
) \
    | tee -a HISTORY
    >CHANGED 
